-d C:\Work\ADC\ADC\impl\gwsynthesis\ADC.vg
-p GW1N-9-LQFP144-6
-pn GW1N-LV9LQ144C6/I5
-cst C:\Work\ADC\ADC\src\ports.cst
-cfg C:\Work\ADC\ADC\impl\pnr\device.cfg
-sdc C:\Work\ADC\ADC\src\ADC.sdc
-bit
-tr
-ph
-timing
-cst_error
